// Code generated by "stringer -type PTYConfig -trimprefix PTY"; DO NOT EDIT.

package opshell

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PTYDefault-0]
	_ = x[PTYForce-1]
	_ = x[PTYDisable-2]
}

const _PTYConfig_name = "DefaultForceDisable"

var _PTYConfig_index = [...]uint8{0, 7, 12, 19}

func (i PTYConfig) String() string {
	if i < 0 || i >= PTYConfig(len(_PTYConfig_index)-1) {
		return "PTYConfig(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PTYConfig_name[_PTYConfig_index[i]:_PTYConfig_index[i+1]]
}
